"""Number sequence puzzle generator.

Each puzzle presents the first several terms of a sequence generated by a
hidden rule; the model must infer the rule and predict the next term.

Supported sequence families:
  - arithmetic:   a_n = a_0 + n*d            (constant difference d)
  - geometric:    a_n = a_0 * r^n            (constant ratio r, integer)
  - quadratic:    a_n = a*n^2 + b*n + c      (second-difference is constant)
  - fibonacci_like: a_n = a_{n-1} + a_{n-2}  (custom seed pair)
  - power:        a_n = a_0 * n^k            (power of index, 1-indexed)

Answers are bare decimal integer strings (no units, no punctuation).
Gold CoT ≤ ~350 tokens (well under the 7 680-token scoring budget).
"""

from __future__ import annotations

import logging
import random
from dataclasses import dataclass
from typing import Callable

from src.generators.common import Example, format_wonderland_prompt

__all__ = ["generate"]

logger = logging.getLogger(__name__)

# ── constants ─────────────────────────────────────────────────────────────────
# NUM_DEMO_PAIRS must equal NUM_SHOWN so that every term referenced in the CoT
# verification step (indices 0..NUM_SHOWN-1) is visible in the prompt.  The
# query asks for term NUM_SHOWN+1 (one beyond the shown set).
NUM_SHOWN: int = 5        # terms shown in the sequence: first NUM_SHOWN
NUM_DEMO_PAIRS: int = NUM_SHOWN  # keep in sync — always equal

_HINT_SEQ = (
    "In this realm, numbers follow a hidden pattern in a magical sequence. "
    "Each term is determined by a secret rule applied to its position."
)


# ── sequence rule dataclass ───────────────────────────────────────────────────

@dataclass(slots=True)
class _SeqRule:
    """A named sequence rule.

    Attributes:
        name:        Short identifier shown in CoT.
        description: Human-readable rule description for the CoT.
        term_fn:     Given zero-based index i, return the i-th term.
        cot_derivation: Short multi-line string showing how the rule is found.
    """

    name: str
    description: str
    term_fn: Callable[[int], int]
    cot_derivation: str


# ── rule builders ─────────────────────────────────────────────────────────────

def _build_arithmetic_rule(rng: random.Random) -> _SeqRule:
    """a_n = start + n*d, zero-indexed."""
    start = rng.randint(-20, 20)
    d = rng.choice([i for i in range(-10, 11) if i != 0])
    return _SeqRule(
        name=f"arithmetic(start={start}, d={d})",
        description=(
            f"arithmetic sequence with first term {start} and common difference {d}: "
            f"each term = previous term + ({d})"
        ),
        term_fn=lambda i, s=start, diff=d: s + i * diff,
        cot_derivation=(
            f"  Difference between consecutive terms: ({d}).\n"
            f"  First term: {start}.\n"
            f"  Rule: a(n) = {start} + n × ({d})."
        ),
    )


def _build_geometric_rule(rng: random.Random) -> _SeqRule:
    """a_n = start * r^n, zero-indexed.  Constrained to keep terms small."""
    start = rng.choice([i for i in range(-6, 7) if i not in (0, 1, -1)])
    r = rng.choice([-3, -2, 2, 3])
    return _SeqRule(
        name=f"geometric(start={start}, r={r})",
        description=(
            f"geometric sequence with first term {start} and common ratio {r}: "
            f"each term = previous term × {r}"
        ),
        term_fn=lambda i, s=start, ratio=r: s * (ratio ** i),
        cot_derivation=(
            f"  Ratio between consecutive terms: {r}.\n"
            f"  First term: {start}.\n"
            f"  Rule: a(n) = {start} × {r}^n."
        ),
    )


def _build_quadratic_rule(rng: random.Random) -> _SeqRule:
    """a_n = a*n^2 + b*n + c, zero-indexed."""
    a = rng.choice([i for i in range(-3, 4) if i != 0])
    b = rng.randint(-5, 5)
    c = rng.randint(-10, 10)
    return _SeqRule(
        name=f"quadratic(a={a},b={b},c={c})",
        description=(
            f"quadratic sequence: a(n) = {a}·n² + {b}·n + {c} "
            f"(second differences are constant = {2 * a})"
        ),
        term_fn=lambda i, qa=a, qb=b, qc=c: qa * i * i + qb * i + qc,
        cot_derivation=(
            f"  First differences are not constant — check second differences.\n"
            f"  Second differences: {2 * a} (constant) → coefficient of n² = {a}.\n"
            f"  Rule: a(n) = {a}·n² + {b}·n + {c}."
        ),
    )


def _build_fibonacci_like_rule(rng: random.Random) -> _SeqRule:
    """a_n = a_{n-1} + a_{n-2}, custom seed pair."""
    f0 = rng.randint(1, 10)
    f1 = rng.randint(1, 10)

    def _fib_term(i: int, seed0: int = f0, seed1: int = f1) -> int:
        if i == 0:
            return seed0
        if i == 1:
            return seed1
        a, b = seed0, seed1
        for _ in range(2, i + 1):
            a, b = b, a + b
        return b

    return _SeqRule(
        name=f"fibonacci_like(f0={f0},f1={f1})",
        description=(
            f"Fibonacci-like sequence starting with {f0}, {f1}: "
            f"each term = sum of the previous two terms"
        ),
        term_fn=_fib_term,
        cot_derivation=(
            f"  Each term equals the sum of the two preceding terms.\n"
            f"  Seeds: a(0)={f0}, a(1)={f1}.\n"
            f"  Rule: a(n) = a(n-1) + a(n-2)."
        ),
    )


# Map exponent → human-readable name; avoids fragile positional list indexing.
_POWER_NAMES: dict[int, str] = {2: "squares", 3: "cubes", 4: "fourth powers", 5: "fifth powers"}


def _build_power_rule(rng: random.Random) -> _SeqRule:
    """a_n = (n+1)^k (1-indexed power), k ∈ {2, 3}."""
    k = rng.choice([2, 3])
    offset = rng.randint(0, 5)
    return _SeqRule(
        name=f"power(k={k},offset={offset})",
        description=(
            f"power sequence: a(n) = (n+1)^{k} + {offset}, "
            f"where n is zero-based (so first term uses n=0)"
        ),
        term_fn=lambda i, exp=k, off=offset: (i + 1) ** exp + off,
        cot_derivation=(
            f"  Terms are perfect {_POWER_NAMES.get(k, f'k={k} powers')} offset by {offset}.\n"
            f"  Pattern: (position)^{k} + {offset}, where position starts at 1.\n"
            f"  Rule: a(n) = (n+1)^{k} + {offset}."
        ),
    )


_RULE_BUILDERS: list[Callable[[random.Random], _SeqRule]] = [
    _build_arithmetic_rule,
    _build_geometric_rule,
    _build_quadratic_rule,
    _build_fibonacci_like_rule,
    _build_power_rule,
]


# ── CoT builder ───────────────────────────────────────────────────────────────

def _build_cot(
    rule: _SeqRule,
    shown_terms: list[int],
    next_index: int,
    answer: int,
) -> str:
    """Build a gold chain-of-thought for a number sequence puzzle.

    Args:
        rule:        The chosen sequence rule.
        shown_terms: The terms shown in the prompt (indices 0..len-1).
        next_index:  Zero-based index of the term to predict.
        answer:      The correct next term value.

    Returns:
        Full CoT string ending in ``\\boxed{answer}``.
    """
    lines: list[str] = []
    lines.append("Let me work through this number sequence puzzle step by step.")
    lines.append("")
    lines.append("**Step 1 — Restate the sequence**")
    terms_str = ", ".join(str(t) for t in shown_terms)
    lines.append(f"  Sequence: {terms_str}, ?")

    lines.append("")
    lines.append("**Step 2 — Induce the rule**")
    lines.append(rule.cot_derivation)

    lines.append("")
    lines.append("**Step 3 — Verify the rule on every shown term**")
    all_pass = True
    for i, t in enumerate(shown_terms):
        predicted = rule.term_fn(i)
        status = "PASS" if predicted == t else "FAIL"
        if status == "FAIL":
            all_pass = False
        lines.append(
            f"  Term {i}: rule gives {predicted} (expected {t}) [{status}]"
        )
    if not all_pass:
        raise ValueError(
            f"[number_seq] Rule '{rule.name}' failed to reproduce its own terms."
        )
    lines.append("  All shown terms verified.")

    lines.append("")
    lines.append("**Step 4 — Apply rule to find the next term**")
    lines.append(f"  Next term index: {next_index}")
    lines.append(f"  a({next_index}) = {answer}")

    lines.append("")
    lines.append("**Step 5 — Final answer**")
    lines.append(f"\\boxed{{{answer}}}")

    return "\n".join(lines)


# ── public entry-point ────────────────────────────────────────────────────────

def generate(n: int, seed: int) -> list[Example]:
    """Generate n number-sequence puzzle Examples.

    Each puzzle shows NUM_SHOWN consecutive terms of a sequence generated by
    a hidden rule and asks for the next term.  Demo pairs are (term_index,
    term_value) formatted as "{index}→{value}" so the Wonderland framing
    shows a clean set of examples.

    Args:
        n:    Number of examples to generate.
        seed: RNG seed for reproducibility.

    Returns:
        List of length n fully-formed Example objects.

    Raises:
        ValueError: If any generated puzzle fails internal consistency check.
    """
    rng = random.Random(seed)
    examples: list[Example] = []

    for idx in range(n):
        builder = rng.choice(_RULE_BUILDERS)
        rule = builder(rng)

        # Generate NUM_SHOWN terms (indices 0..NUM_SHOWN-1); next term is index NUM_SHOWN
        shown_terms: list[int] = [rule.term_fn(i) for i in range(NUM_SHOWN)]
        next_index = NUM_SHOWN
        answer_int = rule.term_fn(next_index)
        answer = str(answer_int)

        # Demo pairs: show consecutive (position, value) examples using 1-based labels
        demo_pairs: list[tuple[str, str]] = [
            (f"term {i + 1}", str(shown_terms[i])) for i in range(NUM_DEMO_PAIRS)
        ]
        # Query asks for the next term position
        query_input = f"term {NUM_SHOWN + 1}"

        prompt = format_wonderland_prompt(
            pairs=demo_pairs,
            query_input=query_input,
            extra_hint=_HINT_SEQ,
        )

        gold_cot = _build_cot(rule, shown_terms, next_index, answer_int)

        expected_box = f"\\boxed{{{answer}}}"
        if not gold_cot.endswith(expected_box):
            raise ValueError(
                f"[number_seq] Example {idx}: gold_cot does not end with "
                f"'{expected_box}'. CoT tail: {gold_cot[-80:]!r}"
            )

        examples.append(
            Example(
                prompt=prompt,
                answer=answer,
                domain="number_seq",
                gold_cot=gold_cot,
            )
        )
        logger.debug(
            "number_seq example %d: rule=%s next_index=%d answer=%s",
            idx, rule.name, next_index, answer,
        )

    return examples
